// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WestWindSystem.Entities
{
    [Index(nameof(CustomerID), Name = "CustomerID")]
    [Index(nameof(CustomerID), Name = "CustomersOrders")]
    [Index(nameof(SalesRepID), Name = "EmployeeID")]
    [Index(nameof(SalesRepID), Name = "EmployeesOrders")]
    [Index(nameof(OrderDate), Name = "OrderDate")]
    public partial class Order
    {
        [Key]
        public int OrderID { get; set; }
        public int? SalesRepID { get; set; }
        [Required]
        [StringLength(5)]
        public string CustomerID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? OrderDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RequiredDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PaymentDueDate { get; set; }
        [Column(TypeName = "money")]
        public decimal? Freight { get; set; }
        public bool Shipped { get; set; }
        [StringLength(40)]
        public string ShipName { get; set; }
        public int? ShipAddressID { get; set; }
        [StringLength(250)]
        public string Comments { get; set; }

        [ForeignKey(nameof(CustomerID))]
        [InverseProperty("Orders")]
        public virtual Customer Customer { get; set; }
    }
}